FROM python:3.11.0
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
RUN pip install django
RUN pip install djangorestframework
RUN pip install django-environ
RUN pip install django-cors-headers
RUN pip install Pillow